export let groupData: any = [
  {
    text: 'Smith',
    id: 'received-01',
    icon: 'e-custom',
    type: 'received',
    group: 'Received',
    time: '2 hours ago',
    category: 'Today',
  },
  {
    text: 'Johnson',
    id: 'received-02',
    icon: 'e-custom',
    type: 'received',
    group: 'Received',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Williams',
    id: 'missed-01',
    icon: 'e-custom',
    type: 'missed',
    group: 'Missed',
    time: '4 hours ago',
    category: 'Today',
  },
  {
    text: 'Jones',
    id: 'missed-02',
    icon: 'e-custom',
    type: 'missed',
    group: 'Missed',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Brown',
    id: 'received-03',
    icon: 'e-custom',
    type: 'received',
    group: 'Received',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Anderson',
    id: 'received-01',
    icon: 'e-custom',
    type: 'received',
    group: 'Received',
    time: '12 hours ago',
    category: 'Today',
  },
  {
    text: 'Thomas',
    id: 'received-02',
    icon: 'e-custom',
    type: 'received',
    group: 'Received',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Jackson',
    id: 'missed-01',
    icon: 'e-custom',
    type: 'missed',
    group: 'Missed',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Emily',
    id: 'missed-01',
    icon: 'e-custom',
    type: 'missed',
    group: 'Missed',
    time: '14 hours ago',
    category: 'Today',
  },
  {
    text: 'White',
    id: 'missed-02',
    icon: 'e-custom',
    type: 'missed',
    group: 'Missed',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Jones',
    id: 'missed-02',
    icon: 'e-custom',
    type: 'missed',
    group: 'Missed',
    time: '18 hours ago',
    category: 'Today',
  },
  {
    text: 'Grace',
    id: 'missed-02',
    icon: 'e-custom',
    type: 'missed',
    group: 'Missed',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Brooklyn',
    id: 'missed-02',
    icon: 'e-custom',
    type: 'missed',
    group: 'Missed',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Arianna',
    id: 'received-01',
    icon: 'e-custom',
    type: 'received',
    group: 'Received',
    time: 'Yesterday',
    category: 'Yesterday',
  },
  {
    text: 'Katherine',
    id: 'received-02',
    icon: 'e-custom',
    type: 'received',
    group: 'Received',
    time: 'Yesterday',
    category: 'Yesterday',
  },
];
